protected/controllers/OrderController.php
<?php

class OrderController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('cart','emptycart'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('index', 'view', 'update', 'admin', 'delete'),
                'users' => array('@'),
                'expression' => 'isset(Yii::app()->user->group) &&
                    ((Yii::app()->user->group==="dolgozó") ||
                    (Yii::app()->user->group==="vezető"))',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Order;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Order'])) {
            $model->attributes = $_POST['Order'];
            var_dump(Yii::app()->user->user_id);
            $model->user_id = Yii::app()->user->user_id;
            if ($model->save()) {
                $success = TRUE;
                foreach ($_SESSION['cart'] as $key => $value) {
                    $plant = Plant::model()->find('name=:name', array('name'=>$key));
                    $orderplant = new OrderPlant();
                    $orderplant->attributes=array('order_id'=>$model->id, 'plant_id'=>$plant->id,'quantity'=>$value);
                    if(!$orderplant->save()){
                        $success = FALSE;
                    }
                }
                if ($success) {
                    unset($_SESSION['cart']);
                    $this->redirect(array('plant/shop'));
                } else {
                    $model->addError('id','Nem sikerült a rendeléshez tartozó termékek felvétele');
                }
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Order'])) {
            $model->attributes = $_POST['Order'];
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax'])) {
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $model = new Order('search');
        $model->unsetAttributes();  // clear any default values
        $this->render('index', array(
            'model' => $model,
        ));
    }

    public function actionCart() {
        $dataProvider = new CActiveDataProvider('Order');
        $this->render('cart', array(
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionEmptyCart() {
        unset($_SESSION['cart']);
        $dataProvider = new CActiveDataProvider('Order');
        $this->render('cart', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Order the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Order::model()->findByPk($id);
        if ($model === null) {
            throw new CHttpException(404, 'The requested page does not exist.');
        }
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Order $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'order-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/controllers/QueryController.php
<?php

class QueryController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('index', 'result'),
                'users' => array('@'),
                'expression' => 'isset(Yii::app()->user->group) &&
                    ((Yii::app()->user->group==="dolgozó") ||
                    (Yii::app()->user->group==="vezető"))',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionIndex() {
        $model = new Query;
        $model->unsetAttributes();
        $model->fromDate = date("Y-m-d", strtotime("-10 days"));
        $model->toDate = date("Y-m-d");

        $this->render('index', array("model" => $model));
    }

    public function actionResult() {
        $model = new Query;
        $model->unsetAttributes();

        if (isset($_POST['Query'])) {
            $rows = array();
            $values = filter_input(INPUT_POST, 'Query', FILTER_DEFAULT, FILTER_REQUIRE_ARRAY);
            $model->attributes = $values;

            if ($model->validate()) {
                switch ($model->type) {
                    case "orders":
                        $orders = Order::model()->with('plants')->findAll('date BETWEEN :from AND :to', array(':from' => strtotime($model->fromDate), ':to' => (strtotime($model->toDate) + 3600 * 24)));
                        if ($orders != null && count($orders) > 0) {
                            $sum = 0;
                            foreach ($orders as $order) {
                                foreach ($order->orderplants as $orderplant) {
                                    $sum += $orderplant->quantity;
                                }
                            }
                            $rows = array(
                                'name' => $model->fromDate . " - " . $model->toDate,
                                'sum' => $sum
                            );
                        }
                        break;
                    case "mostorderedplants":
                        $orderplants = OrderPlant::model()->with('order', 'plant')->findall('order.date BETWEEN :from AND :to', array(':from' => strtotime($model->fromDate), ':to' => (strtotime($model->toDate) + 3600 * 24)));
                        $plants = array();
                        foreach ($orderplants as $orderplant) {
                            if (isset($plants[$orderplant->plant->name])) {
                                $plants[$orderplant->plant->name] += $orderplant->quantity;
                            } else {
                                $plants[$orderplant->plant->name] = $orderplant->quantity;
                            }
                        }
                        arsort($plants);
                        $value = current($plants);
                        $key = key($plants);
                        $rows = array(
                            'name' => $key,
                            'sum' => $value
                        );
                        break;
                    case "leastorderedplants":
                        $orderplants = OrderPlant::model()->with('order', 'plant')->findall('order.date BETWEEN :from AND :to', array(':from' => strtotime($model->fromDate), ':to' => (strtotime($model->toDate) + 3600 * 24)));
                        $plants = array();
                        foreach ($orderplants as $orderplant) {
                            if (isset($plants[$orderplant->plant->name])) {
                                $plants[$orderplant->plant->name] += $orderplant->quantity;
                            } else {
                                $plants[$orderplant->plant->name] = $orderplant->quantity;
                            }
                        }
                        arsort($plants);
                        $value = end($plants);
                        $key = key($plants);
                        $rows = array(
                            'name' => $key,
                            'sum' => $value
                        );
                        break;
                }

                $this->render('result', array('model' => $model, 'rows' => $rows));
            } else {
                $this->redirect(array("index"));
            }
        } else {
            $this->redirect(array("index"));
        }
    }

}

protected/controllers/UserController.php
<?php

class UserController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('register'),
                'users' => array('*'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('create', 'update', 'index', 'view', 'admin', 'delete'),
                'users' => array('@'),
                'expression' => 'isset(Yii::app()->user->group) &&
                    ((Yii::app()->user->group==="dolgozó") ||
                    (Yii::app()->user->group==="vezető"))',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new User;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
            $model->group = "dolgozó";
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionRegister() {
        $model = new User;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax'])) {
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $model = new User('search');
        $model->unsetAttributes();  // clear any default values
        $this->render('index', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return User the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = User::model()->findByPk($id);
        if ($model === null) {
            throw new CHttpException(404, 'The requested page does not exist.');
        }
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param User $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'user-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-24">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="language" content="hu">

        <!-- blueprint CSS framework -->
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
        <!--[if lt IE 8]>
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
        <![endif]-->

        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">

        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    </head>

    <body>

        <div class="container" id="page">

            <div id="header">
                <div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
            </div><!-- header -->

            <div id="mainmenu">
                <div style="float: left">
                    <?php
                    $this->widget('zii.widgets.CMenu', array(
                        'items' => array(
                            array('label' => 'Főoldal', 'url' => array('/plant/shop'), 'visible' => !(isset(Yii::app()->user->group) && ((Yii::app()->user->group === "dolgozó") || (Yii::app()->user->group === "vezető")))),
                            array('label' => 'Kosár', 'url' => array('/order/cart'), 'visible' => !(isset(Yii::app()->user->group) && ((Yii::app()->user->group === "dolgozó") || (Yii::app()->user->group === "vezető")))),
                            array('label' => 'Kontakt', 'url' => array('/site/contact'), 'visible' => !(isset(Yii::app()->user->group) && ((Yii::app()->user->group === "dolgozó") || (Yii::app()->user->group === "vezető")))),
                            array('label' => 'Növények', 'url' => array('/plant/index'), 'visible' => isset(Yii::app()->user->group) && ((Yii::app()->user->group === "dolgozó") || (Yii::app()->user->group === "vezető"))),
                            array('label' => 'Növénytípusok', 'url' => array('/plantType/index'), 'visible' => isset(Yii::app()->user->group) && ((Yii::app()->user->group === "dolgozó") || (Yii::app()->user->group === "vezető"))),
                            array('label' => 'Rendelések', 'url' => array('/order/index'), 'visible' => isset(Yii::app()->user->group) && ((Yii::app()->user->group === "dolgozó") || (Yii::app()->user->group === "vezető"))),
                            array('label' => 'Felhasználók', 'url' => array('/user/index'), 'visible' => isset(Yii::app()->user->group) && ((Yii::app()->user->group === "dolgozó") || (Yii::app()->user->group === "vezető"))),
                            array('label' => 'Lekérdezések', 'url' => array('/query/index'), 'visible' => isset(Yii::app()->user->group) && ((Yii::app()->user->group === "dolgozó") || (Yii::app()->user->group === "vezető"))),
                            array('label' => 'Bejelentkezés', 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
                            array('label' => 'Kijelentkezés', 'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest)
                        ),
                    ));
                    ?>
                </div>
                <div style="float:right; padding: 2px">
                    <?php echo CHtml::form(Yii::app()->createUrl('plant/searchbykeyword'), 'get') ?>
                    <?php echo CHtml::textField('q', 'search') ?>
                    <?php echo CHtml::endForm() ?>
                </div>
                <div style="clear:both"></div>
            </div><!-- mainmenu -->
            <?php if (isset($this->breadcrumbs)): ?>
                <?php
                $this->widget('zii.widgets.CBreadcrumbs', array(
                    'links' => $this->breadcrumbs,
                ));
                ?><!-- breadcrumbs -->
            <?php endif ?>

            <?php echo $content; ?>

            <div class="clear"></div>

            <div id="footer">
                Copyright &copy; <?php echo date('Y'); ?> by RFT team.<br/>
                All Rights Reserved.<br/>
                <?php echo Yii::powered(); ?>
            </div><!-- footer -->

        </div><!-- page -->

    </body>
</html>