protected/models/Plant.php
<?php

/**
 * This is the model class for table "plant".
 *
 * The followings are the available columns in table 'plant':
 * @property string $id
 * @property string $name
 * @property string $type_id
 * @property string $property
 * @property string $requirement
 * @property string $plantable_from
 * @property string $plantable_to
 * @property string $quantity
 * @property string $price
 *
 * The followings are the available model relations:
 * @property Order[] $orders
 * @property PlantType $type
 */
class Plant extends CActiveRecord {

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'plant';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('name, type_id, property, requirement, plantable_from, plantable_to, quantity, price', 'required'),
            array('name', 'length', 'max' => 50),
            array('type_id, plantable_from, plantable_to, quantity, price', 'length', 'max' => 10),
            array('property, requirement', 'safe'),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('id, name, type_id, property, requirement, plantable_from, plantable_to, quantity, price', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'orders' => array(self::MANY_MANY, 'Order', 'order_plant(plant_id, order_id)'),
            'type' => array(self::BELONGS_TO, 'PlantType', 'type_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'name' => 'Név',
            'type_id' => 'Típus',
            'property' => 'Jellemzők',
            'requirement' => 'Igények',
            'plantable_from' => 'Ültethető (tól)',
            'plantable_to' => 'Ültethető (ig)',
            'quantity' => 'Raktáron',
            'price' => 'Ár',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search() {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('type_id', $this->type_id, true);
        $criteria->compare('property', $this->property, true);
        $criteria->compare('requirement', $this->requirement, true);
        $criteria->compare('plantable_from', $this->plantable_from, true);
        $criteria->compare('plantable_to', $this->plantable_to, true);
        $criteria->compare('quantity', $this->quantity, true);
        $criteria->compare('price', $this->price, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Plant the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

}

protected/models/PlantType.php
<?php

/**
 * This is the model class for table "plant_type".
 *
 * The followings are the available columns in table 'plant_type':
 * @property string $id
 * @property string $name
 * @property string $description
 * @property string $unit
 *
 * The followings are the available model relations:
 * @property Plant[] $plants
 */
class PlantType extends CActiveRecord {

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'plant_type';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('name, unit', 'required'),
            array('name', 'length', 'max' => 50),
            array('unit', 'length', 'max' => 5),
            array('unit', 'in', 'range' => array('darab', 'tő', 'szál')),
            array('description', 'safe'),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('id, name, description, unit', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'plants' => array(self::HAS_MANY, 'Plant', 'type_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'name' => 'Név',
            'description' => 'Leírás',
            'unit' => 'Egység',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search() {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('description', $this->description, true);
        $criteria->compare('unit', $this->unit, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return PlantType the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

}

protected/controllers/PlantController.php
<?php

class PlantController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('shop', 'shopitem', 'addtocart', 'searchbykeyword'),
                'users' => array('*'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('index', 'view', 'create', 'update', 'admin', 'delete'),
                'users' => array('@'),
                'expression' => 'isset(Yii::app()->user->group) &&
                    ((Yii::app()->user->group==="dolgozó") ||
                    (Yii::app()->user->group==="vezető"))',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Plant;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Plant'])) {
            $model->attributes = $_POST['Plant'];
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Plant'])) {
            $model->attributes = $_POST['Plant'];
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax'])) {
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $model = new Plant('search');
        $model->unsetAttributes();  // clear any default values
        $this->render('index', array(
            'model' => $model,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionShop() {
        $criteria = (isset($_GET['planttype_id']) && $_GET['planttype_id'] != "") ?
                array(
            'condition' => 'type_id=' . $_GET['planttype_id'],
            'order' => 'id ASC',
                ) : array(
            'order' => 'id ASC',
        );
        $options = array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => 20,
            ),
        );
        $dataProvider = new CActiveDataProvider('Plant', $options);
        // retrieve categories from db for the dropdown list
        $models = PlantType::model()->findAll(array('order' => 'name'));
        // format categories as $key=>$value with listData
        $list = CHtml::listData($models, 'id', 'name');
        $selected_category_id = (isset($_GET['planttype_id'])) ? $_GET['planttype_id'] : "";

        $this->render('shop', array(
            'dataProvider' => $dataProvider,
            'list' => $list,
            'selected_category_id' => $selected_category_id,
        ));
    }

    public function actionAddtocart($id) {
        if (!isset($_SESSION['cart'])) {
            $_SESSION['cart'] = array();
        }

        $plant = Plant::model()->findByPk($id);
        if (isset($_SESSION['cart'][$plant->name])) {
            $_SESSION['cart'][$plant->name] ++;
        } else {
            $_SESSION['cart'][$plant->name] = 1;
        }
        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('shop'));
    }

    public function actionSearchByKeyword($q) {
        //based on the shop method's type filtering
        $criteria = (isset($_GET['q']) && $_GET['q'] != "") ?
                array(
            'condition' => "name LIKE '%" . $_GET['q']."%' OR property LIKE '%" . $_GET['q']."%' OR requirement LIKE '%" . $_GET['q']."%'",
            'order' => 'id ASC',
                ) : array(
            'order' => 'id ASC',
        );
        $options = array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => 20,
            ),
        );
        $dataProvider = new CActiveDataProvider('Plant', $options);
        $keyword = (isset($_GET['q'])) ?  CHtml::encode($_GET['q']) : "";

        $this->render('keyword', array(
            'dataProvider' => $dataProvider,
            'keyword' => $keyword,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Plant the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Plant::model()->findByPk($id);
        if ($model === null) {
            throw new CHttpException(404, 'The requested page does not exist.');
        }
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Plant $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'plant-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/plant/_form.php
<?php
/* @var $this PlantController */
/* @var $model Plant */
/* @var $form CActiveForm */
?>

<div class="form">

    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'plant-form',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation' => false,
    ));
    ?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo $form->labelEx($model, 'name'); ?>
        <?php echo $form->textField($model, 'name', array('size' => 50, 'maxlength' => 50)); ?>
        <?php echo $form->error($model, 'name'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'type_id'); ?>
        <?php
        $list = CHtml::listData(PlantType::model()->findAll(), 'id', 'name');
        echo $form->dropDownList($model, 'type_id', $list);
        ?>
        <?php echo $form->error($model, 'type_id'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'property'); ?>
        <?php echo $form->textArea($model, 'property', array('rows' => 6, 'cols' => 50)); ?>
        <?php echo $form->error($model, 'property'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'requirement'); ?>
        <?php echo $form->textArea($model, 'requirement', array('rows' => 6, 'cols' => 50)); ?>
        <?php echo $form->error($model, 'requirement'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'plantable_from'); ?>
        <?php echo $form->textField($model, 'plantable_from', array('size' => 10, 'maxlength' => 10)); ?>
        <?php echo $form->error($model, 'plantable_from'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'plantable_to'); ?>
        <?php echo $form->textField($model, 'plantable_to', array('size' => 10, 'maxlength' => 10)); ?>
        <?php echo $form->error($model, 'plantable_to'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'quantity'); ?>
        <?php echo $form->textField($model, 'quantity', array('size' => 10, 'maxlength' => 10)); ?>
        <?php echo $form->error($model, 'quantity'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'price'); ?>
        <?php echo $form->textField($model, 'price', array('size' => 10, 'maxlength' => 10)); ?>
        <?php echo $form->error($model, 'price'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/plant/_search.php
<?php
/* @var $this PlantController */
/* @var $model Plant */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'type_id'); ?>
		<?php echo $form->textField($model,'type_id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'property'); ?>
		<?php echo $form->textArea($model,'property',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'requirement'); ?>
		<?php echo $form->textArea($model,'requirement',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'plantable_from'); ?>
		<?php echo $form->textField($model,'plantable_from',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'plantable_to'); ?>
		<?php echo $form->textField($model,'plantable_to',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'quantity'); ?>
		<?php echo $form->textField($model,'quantity',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'price'); ?>
		<?php echo $form->textField($model,'price',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/plant/_view.php
<?php
/* @var $this PlantController */
/* @var $data Plant */
?>

<div class="view">

    <b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
    <?php echo CHtml::encode($data->name); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('type_id')); ?>:</b>
    <?php echo CHtml::encode($data->type->name); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('property')); ?>:</b>
    <?php echo CHtml::encode($data->property); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('requirement')); ?>:</b>
    <?php echo CHtml::encode($data->requirement); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('plantable_from')); ?>:</b>
    <?php echo CHtml::encode($data->plantable_from); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('plantable_to')); ?>:</b>
    <?php echo CHtml::encode($data->plantable_to); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('quantity')); ?>:</b>
    <?php echo CHtml::encode($data->quantity); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('price')); ?>:</b>
    <?php echo CHtml::encode($data->price); ?>
    <br />
    
    <?php
    echo CHtml::link('Kosárba',array('plant/addtocart','id'=>$data->id));
    ?>



</div>

protected/views/plant/create.php
<?php
/* @var $this PlantController */
/* @var $model Plant */

$this->breadcrumbs=array(
	'Plants'=>array('index'),
	'Hozzáadás',
);
?>

<h1>Növény hozzáadása</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/plant/index.php
<?php
/* @var $this PlantController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
    'Növények',
);
?>

<h1>Növények</h1>

<?php
echo CHtml::link('Új hozzáadása', array('plant/create'));
$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $model->search(),
    'filter' => $model,
    'columns' => array(
        'id',
        'name',
        array(
            'name' => 'type_id',
            'value' => '$data->type->name',
        ),
        'property',
        'requirement',
        'plantable_from',
        'plantable_to',
        'quantity',
        'price',
        array(
            'class' => 'CButtonColumn',
        ),
    ),
));
?>

protected/views/plant/keyword.php
<?php
/* @var $this PlantController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
    'Növények',
);
?>

<h1><?php echo $keyword; ?> találatok</h1>

<?php
$this->widget('zii.widgets.CListView', array(
    'dataProvider' => $dataProvider,
    'itemView' => '_view',
));
?>

protected/views/plant/shop.php
<?php
/* @var $this PlantController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
    'Növények',
);
?>

<h1>Növények</h1>

<div class="form">

    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'menu-dropdown-form',
        'enableAjaxValidation' => true,
    ));

    echo CHtml::dropDownList('planttype_id', $selected_category_id, // The selected category set on controller action
            $list, // the dropdown options set on controller action
            array('prompt' => 'Select Category',)
    );

    $this->endWidget();
    ?>
</div>

<?php
$this->widget('zii.widgets.CListView', array(
    'dataProvider' => $dataProvider,
    'itemView' => '_view',
    'id' => 'items_list' //for filtering
));


Yii::app()->clientScript->registerScript('items_update', "$('#planttype_id').change(function(){
        $.fn.yiiListView.update('items_list', {
                data: $(this).serialize(),
            }
        );
    });
    return false;", CClientScript::POS_READY);
?>

protected/views/plant/update.php
<?php
/* @var $this PlantController */
/* @var $model Plant */

$this->breadcrumbs=array(
	'Plants'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Plant', 'url'=>array('index')),
	array('label'=>'Create Plant', 'url'=>array('create')),
	array('label'=>'View Plant', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Plant', 'url'=>array('admin')),
);
?>

<h1>Update Plant <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/plant/view.php
<?php
/* @var $this PlantController */
/* @var $model Plant */

$this->breadcrumbs=array(
	'Plants'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Plant', 'url'=>array('index')),
	array('label'=>'Create Plant', 'url'=>array('create')),
	array('label'=>'Update Plant', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Plant', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Plant', 'url'=>array('admin')),
);
?>

<h1>View Plant #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		'type_id',
		'property',
		'requirement',
		'plantable_from',
		'plantable_to',
		'quantity',
		'price',
	),
)); ?>